#!/bin/sh
set -x

export __EGL_VENDOR_LIBRARY_DIRS=$SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}
