name: mir-kiosk-x11-example     # YOUR SNAP NAME GOES HERE
version: '0.1'                  # YOUR SNAP VERSION GOES HERE
summary: example X11 kiosk      # YOUR SUMMARY GOES HERE
description: example X11 kiosk  # YOUR DESCRIPTION GOES HERE
base: core20
confinement: strict
grade: devel

apps:
  mir-kiosk-x11-example:
    daemon: simple
    restart-condition: always
    command-chain:
      - env-setup
    command: usr/local/bin/x11_kiosk_launch bash $SNAP/bin/run_x_server.sh #bash -c "xhost +si:localuser:robot; sleep 100000000"

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  ### YOUR PART GOES HERE
  glxgears:
    plugin: nil
    stage-packages:
      - mesa-utils
      - x11-xserver-utils
    stage-snaps: [mir-kiosk-x11]
  wrapper:
    source: .
    plugin: dump
    organize:
      run_x_server.sh: bin/run_x_server.sh

# Needed by Mir and/or Xwayland
layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts

plugs:
  opengl:         # For Mir
  wayland:        # For Mir
  network-bind:   # For Mir (to serve X11)
